### ISSUE TITLE
[GeneralWindow] new/open/save/close

### ISSUE THREAD

**Issue by PtiLuky** [PtiLuky/dummyeditor#4]
Rendre ces actions fonctionnelles sur GeneralWindow : 

- déclarer les slots dans le .hpp avec les bons noms pour profiter des connexions automatiques
- implémenter les méthodes new/save/close
  - si pour faire une de ces actions cela demande une méthode complexe liée au projet et pas à l'interface -> la mettre dans le classe editor/project

**Comment by Abydox** [comment]
Done

**Comment by Abydox** [comment]
Done
