### ISSUE TITLE
Zoom management

### ISSUE THREAD

**Issue by PtiLuky** [PtiLuky/dummyeditor#8]
Create tools to manage zoom level of the mapGraphicScene, 
including : zoom +, zoom -, reset zoom, shortcuts

**Comment by Abydox** [comment]
- link resize to shortcut Ctrl+midbutton
- link zoom In/Out to shortcut Ctrl+wheelangle
- link horizontal motion to shortcut shit+wheel
- add scroolbar for zoom %
- Fix the fact zoom still affect map when not in maptab
